/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PartOutRouteImport } from './routes/part-out'
import { Route as PartInputRouteImport } from './routes/part-input'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FifoRouteImport } from './routes/fifo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PartOutRoute = PartOutRouteImport.update({
  id: '/part-out',
  path: '/part-out',
  getParentRoute: () => rootRouteImport,
} as any)
const PartInputRoute = PartInputRouteImport.update({
  id: '/part-input',
  path: '/part-input',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FifoRoute = FifoRouteImport.update({
  id: '/fifo',
  path: '/fifo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fifo': typeof FifoRoute
  '/login': typeof LoginRoute
  '/part-input': typeof PartInputRoute
  '/part-out': typeof PartOutRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fifo': typeof FifoRoute
  '/login': typeof LoginRoute
  '/part-input': typeof PartInputRoute
  '/part-out': typeof PartOutRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fifo': typeof FifoRoute
  '/login': typeof LoginRoute
  '/part-input': typeof PartInputRoute
  '/part-out': typeof PartOutRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fifo'
    | '/login'
    | '/part-input'
    | '/part-out'
    | '/production'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fifo'
    | '/login'
    | '/part-input'
    | '/part-out'
    | '/production'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fifo'
    | '/login'
    | '/part-input'
    | '/part-out'
    | '/production'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FifoRoute: typeof FifoRoute
  LoginRoute: typeof LoginRoute
  PartInputRoute: typeof PartInputRoute
  PartOutRoute: typeof PartOutRoute
  ProductionRoute: typeof ProductionRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-out': {
      id: '/part-out'
      path: '/part-out'
      fullPath: '/part-out'
      preLoaderRoute: typeof PartOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-input': {
      id: '/part-input'
      path: '/part-input'
      fullPath: '/part-input'
      preLoaderRoute: typeof PartInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifo': {
      id: '/fifo'
      path: '/fifo'
      fullPath: '/fifo'
      preLoaderRoute: typeof FifoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FifoRoute: FifoRoute,
  LoginRoute: LoginRoute,
  PartInputRoute: PartInputRoute,
  PartOutRoute: PartOutRoute,
  ProductionRoute: ProductionRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
